### ISSUE TITLE
Audio decoder test panic

### ISSUE THREAD

**Issue by ferjm** [servo/media#136]
```
thread 'main' panicked at 'assertion failed: buf.len() == buffers[0].len()', audio/src/buffer_source_node.rs:206:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at libstd/panicking.rs:411
   6: servo_media_audio::buffer_source_node::AudioBuffer::from_buffers
             at audio/src/buffer_source_node.rs:206
   7: <servo_media_audio::buffer_source_node::AudioBuffer as core::convert::From<alloc::vec::Vec<alloc::vec::Vec<f32>>>>::from
             at audio/src/buffer_source_node.rs:233
   8: <T as core::convert::Into<U>>::into
             at libcore/convert.rs:456
   9: audio_decoder::run_example
             at examples/audio_decoder.rs:67
  10: audio_decoder::main
             at examples/audio_decoder.rs:77
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: <unknown>
```

**Comment by mrobinson** [comment]
Haven't seen this one.
